inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  Enabled: false

Metrics:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
