inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Style/AccessModifierDeclarations:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false
